### ISSUE TITLE
Table Importer: Could not resolve file name 'table.csv'.

### ISSUE THREAD

**Issue by laurathomas** [Perlkonig/grav-plugin-table-importer#10]
Hi,
Useful concept for one of my clients as they use a lot of tables in their Grav build, but coming up with the error:

`Table Importer: Could not resolve file name 'table.csv'.`

I have the CSV file in the same directory from where I'm calling it from and my code is just the basic:

`[ti file=table.csv enclosure=']`

Any ideas? Thanks

**Comment by Perlkonig** [comment]
There does appear to be some weirdness. I'm looking into it. I see you closed this. You resolved it?

**Comment by Perlkonig** [comment]
Just released a new version that fixes a bug with abbreviated shortcodes, which was not your problem. Don't hesitate to reopen if you're still having issues.

**Comment by laurathomas** [comment]
Thanks for getting back to me so quick. Haha I'm a dunce, the error was my fault, I quickly realised and closed the issue.



Really great plugin, useful for those clients who love an Excel sheet!



Thanks again 




---- On Thu, 06 Jul 2017 15:34:08 +0100 Aaron Dalton &lt;notifications@github.com&gt; wrote ----



Just released a new version that fixes a bug with abbreviated shortcodes, which was not your problem. Don't hesitate to reopen if you're still having issues.

**Comment by Perlkonig** [comment]
Glad you're finding it useful.

**Comment by thekenshow** [comment]
Great plugin, will really make some clients happy :-) 

I'm running into this problem repeatedly, say 50% of the time, after editing a page. My pages use a custom blueprint but with the standard Markdown content field. They **are working fine**, and then the error occurs **without any changes to the shortcode or CSV file name**. 

I get:

```
Table Importer: Could not resolve file name 'myDataFile.csv'.
```

Example field content:

```
<section class="offs-xxl">
  <div class="container">
    <div class="item-content">
      <div class="lead">Genuine Mackie Thump Series replacement parts.</div>
        <p>[ti file=Thump-Series-MACKIE-THUMP-SERIES.csv class="table table-hover"]</p>
      </div>
    </div>
</section>
```

It even seems affect more than the page being edited, so maybe a caching problem? Another guess:  interaction between editing `custompage.md` directly and in the Admin.
