### ISSUE TITLE
Link inside of the table

### ISSUE THREAD

**Issue by xieciun** [Perlkonig/grav-plugin-table-importer#14]
Hi,

I am trying to put a link to another web page inside of the table created with Table Importer. I have tried different things, but nothing works.

Any advice?

**Comment by Perlkonig** [comment]
I do this on my personal blog (https://www.perlkonig.com/blog/podcasts-2016). You have to put raw HTML in the CSV file (actual `<a>` tags).

**Comment by xieciun** [comment]
Hi,
Thank you for the super quick answer. I believe that there must be some additional detail as I have tried this and the <a>... code is displayed in the table itself. You can see the screen from the page, the source and csv in the attached file

![table_links](https://user-images.githubusercontent.com/20596332/33751942-abdeb666-dbde-11e7-9644-cd9fddf56216.png)

**Comment by Perlkonig** [comment]
In the docs you will see a line about the `raw` option:

> By default, the content of each cell is escaped using PHP's `htmlspecialchars` function. If the `raw` option is set to anything at all, the escaping will be disabled. **Only do this if you trust the incoming data!**

So here's the tag that creates that list of podcasts I linked to earlier:

```
[ti file=bp-2016.csv raw="true" /]
```
