### ISSUE TITLE
Table does not import in blog archive output

### ISSUE THREAD

**Issue by crusnac** [Perlkonig/grav-plugin-table-importer#15]
My csv files import successfully while pointing directly on the page, but when I am viewing multiple pages via a blog view, I get the following error:

`Table Importer: Could not resolve file name 'filename.csv'.`

I suspect that this is caused by the table importer using a relative URL to load the .csv file.

**Comment by Perlkonig** [comment]
Replicated. The problem is that `$this->grav['page']->path()` doesn't actually return the blog entry's page path but the path of the page containing all the previews. Trying to find a workaround.

**Comment by Perlkonig** [comment]
I can confirm that moving the table to the `user/data` folder works. See the docs for instructions. I'm still looking for a general solution, though.

**Comment by gamahachaa** [comment]
Hi there,

I have a similar issue here.
If cache is deactivated no problem.
As soon as it is activated I have a 
`Table Importer: Could not resolve file name 'filename.csv'.` 
displaying

**Comment by Perlkonig** [comment]
Make sure you're using the latest Grav and Shortcode Core plugins. I don't appear to have caching issues on my dev server: <https://www.perlkonig.com/dev/demos/table-importer>. If you open the debug bar, it will tell you when you're getting a cache hit or not.

If you can't resolve it, or if you get something different on my dev server, let me know and we'll see what we can do. The caching is supposed to be handled by the Shortcode Core plugin. All my code does is return some HTML.

**Comment by gamahachaa** [comment]
Hi Aaron,

Thanks for your reply.
Updating the Shortcode plugin solved it !

And many thanks for this great and very usefull plugin.

Br
Bruno
