### ISSUE TITLE
array_merge(): Argument #2 is not an array

### ISSUE THREAD

**Issue by GracefulForm** [Perlkonig/grav-plugin-table-importer#4]
**Error Received:**
array_merge(): Argument #2 is not an array

**Line Specified:**
   if (isset($page->header()->{'table-importer'})) {
            $this->config->set('plugins.table-importer', array_merge($defaults, $page->header()->{'table-importer'}));
        }

**CSV sample data used:**
Name,Status,Notes
John,Active,Twice per week
Susan,Inactive,Pending surgery
Harry,Active,Traveling to New York

**Comment by Perlkonig** [comment]
Please post the front matter of the page in question. Thanks!

**Comment by GracefulForm** [comment]
Thank you for your time..

**Here is the Frontmatter:**
title: Assigned
table-importer: 'active: true'

**Here is the content:**
[TableImporter>test.csv]

**Comment by Perlkonig** [comment]
It needs to be:

``` yaml
table-importer:
  active: true
```

Reopen if you still have trouble.

**Comment by GracefulForm** [comment]
Okay. I changed it to match yours, and my output on the live page is the shortcode:

[TableImporter>test.csv]

**Comment by Perlkonig** [comment]
Be sure to clear your cache. And `test.csv` is in `user/data/$datadir` where `$datadir` is in the config file?

Version 2.0 is coming in the next couple of days which will standardize the plugin to use the proper shortcode infrastructure. It will eliminate the need for all that front matter.

**Comment by GracefulForm** [comment]
Okay. I had the file in the user/data folder. I created a folder inside the user/data directory called hp and added the datadir to my frontmatter:

title: Assigned
table-importer:
    active: true
    datadir: hp

Now I can see my data and it is responsive, but the sorting is not available.

**Comment by GracefulForm** [comment]
My apologies- The table is imported and I can see it. I still need to go back and view the help file steps for the table sorter- a different plug in all together.

Thank you for your help!

**Comment by Perlkonig** [comment]
Glad you got it working. Table Sorter is separate, yes. The new version of Table Importer should be easier to get working. Cheers!
