### ISSUE TITLE
v2.1.2 do not work.

### ISSUE THREAD

**Issue by cogito-eje** [Perlkonig/grav-plugin-table-importer#6]
I followed the installation, table importer and short are active.
But the content [ti file=import.csv/] is not parsed.

**Comment by cogito-eje** [comment]
Here is the code :

![screenshot-256](https://cloud.githubusercontent.com/assets/25110484/21989657/0b1995a2-dc0c-11e6-8941-89aecb421a5b.png)

This is the result :

![screenshot-255](https://cloud.githubusercontent.com/assets/25110484/21989675/21198402-dc0c-11e6-978c-74ae9927af94.png)

TableImporter is enabled

![screenshot-257](https://cloud.githubusercontent.com/assets/25110484/21989763/75a33e64-dc0c-11e6-937a-464486f58c7b.png)

**Comment by Perlkonig** [comment]
And `import.csv` is in the same folder as the `.md` file?

**Comment by cogito-eje** [comment]
Yes !

![screenshot-258](https://cloud.githubusercontent.com/assets/25110484/21989907/0ffd5904-dc0d-11e6-9eee-e12e8ac46563.png)

**Comment by Perlkonig** [comment]
Can you zip up your `user` folder and send it to me? I'll need to replicate on a dev server. It's hard to debug this sort of thing. The screen shots are helpful :) Merci!

**Comment by cogito-eje** [comment]
Ok I will send in 5 minutes to you a minimal project.
Thanks !

**Comment by Perlkonig** [comment]
Take your time.

**Comment by cogito-eje** [comment]
Here is the file : 

[user.zip](https://github.com/Perlkonig/grav-plugin-table-importer/files/708860/user.zip)

Merci beaucoup 👍

**Comment by Perlkonig** [comment]
I'm still trying to figure out what's happening. My own sites are working fine, but your user folder is not, even after some tweaking. I need a little time. Désolé!

**Comment by cogito-eje** [comment]
Good luck !
I find try to find some things in my side.
Best regards,
Eric Jean-Elie

**Comment by cogito-eje** [comment]
I used a last pure fresh installed GRAV CORE + ADMIN PLUGIN.
I have just installed the TableImporter plugin.
But it doesn't work.

**Comment by Perlkonig** [comment]
The Admin plugin is breaking things, with my other plugins, too. Trying to figure it out. [It works fine with a clean install without the Admin module.](https://perlkonig.com/scratch/clean/)

**Comment by Perlkonig** [comment]
https://github.com/getgrav/grav-plugin-admin/issues/936

**Comment by Perlkonig** [comment]
New version forthcoming that will hopefully fix this problem.
