### ISSUE TITLE
shortcode into cell

### ISSUE THREAD

**Issue by mutek** [Perlkonig/grav-plugin-table-importer#9]
Hello,
thank you in advance for your works,
I need to render shortcodes into cells (i.e links)
Building standard table using markdown works as expected:
|Name|Surname|Picture|
|---|---|---|
|Luther|Blissett|[Luther Icon](luther-icon.png)|

produce a table with the Picture column rendering a link relative to a .png into a local grav folder where default.md page was called

now if I put into the csv the shortcode it's not parsed:
test:
Name,Surname,Picture
Luther,Blissett,[u]https://upload.wikimedia.org/wikipedia/commons/0/02/Luther_Blissett.jpg[/u]

at the end the shortcode was not parsed

thank you for your collaboration
kindly regards

**Comment by Perlkonig** [comment]
This has to do with the order in which Grav processes the shortcodes. As it stands, the base Markdown processing is done before the shortcodes are processed. There's no simple way around this.

I ran into this myself on my own blog (https://www.perlkonig.com/blog/podcasts-2016), and it's what prompted me to add the `raw` option to the plugin. You have to actually use HTML in the CSV file and then enable the `raw` option.

Sorry there's no simple fix!
